### ISSUE TITLE
company.json is not a valid JSON

### ISSUE THREAD

**Issue by danielepolencic** [Mergermarket-Careers/react-frontend-test#1]
`company.json` is not valid JSON.

https://github.com/Mergermarket-Careers/react-frontend-test/blob/9b777d6634f6a788510ec186b45a7b9c0d413db2/company.json

You could either:

- rename it to `company.js`. Indeed the code is valid JS code
- make it a valid JSON by dropping the value assignment

**Comment by aceakash** [comment]
@danielepolencic indeed! Fixed in b159e0f 👍
